### PR TITLE
Namespace & Tests fix 

### PR DESCRIPTION
**Pull request by logbon72**
- Namespaced stream functions to prevent conflicting 
- Fixed tests failing due to errors being thrown.

### CODE REVIEW

**Comment by abdulapopoola** [comment]
Thanks a lot for this! And sorry for the extremely late response - got a bit busy and my bad :-1:.

The namespace issue is a valid concern but personally I prefer not injecting stuff directly into the prototype. However a fix might be to wrap things in an IIFE? Would that work?

Thanks a lot once again for the time and effort on this! By the way, would you want to collaborate on a Naija-style FOSS project? Maybe sometime in the future?

**Comment by logbon72** [comment]
Yeah, my immediate approach was to use IIFE,  but gave up after a while because jsdoc2md was not picking up the documentation of the methods, probably because they were not defined within the global scope. 

As per FOSS will be interested in whatever makes it "Naija-style", but yeah I am open to such.

**Comment by abdulapopoola** [comment]
Ahh,the jsdoc failure is a new one. Created issue #4.

**Comment by abdulapopoola** [comment]
Closing as the API has moved farther ahead.

**Pull request closed without merging**
